/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddPartnerInput {
  'websiteUrl' : string,
  'name' : string,
  'logoUrl' : string,
  'isVerified' : boolean,
  'contactEmail' : string,
  'specialization' : string,
  'contactPhone' : string,
}
export interface AddPropertyInput {
  'latitude' : number,
  'title' : string,
  'featured' : boolean,
  'plotBoundary' : [] | [string],
  'tags' : Array<string>,
  'description' : string,
  'legalStatus' : LegalStatus,
  'constructionFields' : [] | [ConstructionSiteFields],
  'longitude' : number,
  'notes' : [] | [string],
  'isConstructionSite' : boolean,
  'contactWhatsApp' : [] | [string],
  'price' : bigint,
  'locationName' : string,
  'areaSizeSqFt' : number,
  'contactPhone' : [] | [string],
}
export interface BuilderPartner {
  'id' : string,
  'websiteUrl' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'logoUrl' : string,
  'isVerified' : boolean,
  'contactEmail' : string,
  'specialization' : string,
  'contactPhone' : string,
}
export interface ConstructionSiteFields {
  'currentPhase' : string,
  'expectedCompletionDate' : string,
  'constructionStartDate' : string,
  'progressPercentage' : bigint,
  'sitePhotos' : Array<ExternalBlob>,
  'liveUpdates' : string,
}
export interface DealerProfile {
  'bio' : string,
  'name' : string,
  'designation' : string,
  'photoUrl' : string,
  'instagramUrl' : string,
  'email' : string,
  'experience' : string,
  'whatsappNumber' : string,
  'phone' : string,
  'facebookUrl' : string,
  'linkedinUrl' : string,
}
export type ExternalBlob = Uint8Array;
export type LegalStatus = { 'not_approved' : null } |
  { 'approved' : null };
export interface Property {
  'status' : PropertyStatus,
  'latitude' : number,
  'title' : string,
  'featured' : boolean,
  'ownerId' : Principal,
  'plotBoundary' : [] | [string],
  'tags' : Array<string>,
  'primaryImageIndex' : bigint,
  'description' : string,
  'propertyId' : PropertyId,
  'viewCount' : bigint,
  'legalStatus' : LegalStatus,
  'constructionFields' : [] | [ConstructionSiteFields],
  'longitude' : number,
  'notes' : [] | [string],
  'isConstructionSite' : boolean,
  'contactWhatsApp' : [] | [string],
  'price' : bigint,
  'locationName' : string,
  'areaSizeSqFt' : number,
  'contactPhone' : [] | [string],
  'dateAdded' : Timestamp,
  'images' : Array<ExternalBlob>,
}
export type PropertyId = string;
export type PropertyStatus = { 'sold' : null } |
  { 'available' : null };
export type Timestamp = bigint;
export interface UpdatePartnerInput {
  'websiteUrl' : [] | [string],
  'name' : [] | [string],
  'logoUrl' : [] | [string],
  'isVerified' : [] | [boolean],
  'contactEmail' : [] | [string],
  'specialization' : [] | [string],
  'contactPhone' : [] | [string],
}
export interface UpdatePropertyInput {
  'latitude' : [] | [number],
  'title' : [] | [string],
  'featured' : [] | [boolean],
  'plotBoundary' : [] | [string],
  'tags' : [] | [Array<string>],
  'primaryImageIndex' : [] | [bigint],
  'description' : [] | [string],
  'legalStatus' : [] | [LegalStatus],
  'constructionFields' : [] | [ConstructionSiteFields],
  'longitude' : [] | [number],
  'notes' : [] | [string],
  'isConstructionSite' : [] | [boolean],
  'contactWhatsApp' : [] | [string],
  'price' : [] | [bigint],
  'locationName' : [] | [string],
  'areaSizeSqFt' : [] | [number],
  'contactPhone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addImageToProperty' : ActorMethod<[PropertyId, ExternalBlob], undefined>,
  'addPartner' : ActorMethod<[AddPartnerInput], string>,
  'addProperty' : ActorMethod<[AddPropertyInput], PropertyId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePartner' : ActorMethod<[string], undefined>,
  'deleteProperty' : ActorMethod<[PropertyId], undefined>,
  'getAllPartners' : ActorMethod<[], Array<BuilderPartner>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDealerProfile' : ActorMethod<[], [] | [DealerProfile]>,
  'getPartner' : ActorMethod<[string], [] | [BuilderPartner]>,
  'getProperty' : ActorMethod<[PropertyId], [] | [Property]>,
  'incrementViewCount' : ActorMethod<[PropertyId], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeImageFromProperty' : ActorMethod<[PropertyId, bigint], undefined>,
  'reorderImages' : ActorMethod<[PropertyId, Array<bigint>], undefined>,
  'setDealerProfile' : ActorMethod<[DealerProfile], undefined>,
  'setPrimaryImageIndex' : ActorMethod<[PropertyId, bigint], undefined>,
  'setPropertyStatus' : ActorMethod<[PropertyId, PropertyStatus], undefined>,
  'updatePartner' : ActorMethod<[string, UpdatePartnerInput], undefined>,
  'updateProperty' : ActorMethod<[PropertyId, UpdatePropertyInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];