/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PropertyId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AddPartnerInput = IDL.Record({
  'websiteUrl' : IDL.Text,
  'name' : IDL.Text,
  'logoUrl' : IDL.Text,
  'isVerified' : IDL.Bool,
  'contactEmail' : IDL.Text,
  'specialization' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const LegalStatus = IDL.Variant({
  'not_approved' : IDL.Null,
  'approved' : IDL.Null,
});
export const ConstructionSiteFields = IDL.Record({
  'currentPhase' : IDL.Text,
  'expectedCompletionDate' : IDL.Text,
  'constructionStartDate' : IDL.Text,
  'progressPercentage' : IDL.Nat,
  'sitePhotos' : IDL.Vec(ExternalBlob),
  'liveUpdates' : IDL.Text,
});
export const AddPropertyInput = IDL.Record({
  'latitude' : IDL.Float64,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'plotBoundary' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'legalStatus' : LegalStatus,
  'constructionFields' : IDL.Opt(ConstructionSiteFields),
  'longitude' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'isConstructionSite' : IDL.Bool,
  'contactWhatsApp' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
  'locationName' : IDL.Text,
  'areaSizeSqFt' : IDL.Float64,
  'contactPhone' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const BuilderPartner = IDL.Record({
  'id' : IDL.Text,
  'websiteUrl' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'logoUrl' : IDL.Text,
  'isVerified' : IDL.Bool,
  'contactEmail' : IDL.Text,
  'specialization' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const PropertyStatus = IDL.Variant({
  'sold' : IDL.Null,
  'available' : IDL.Null,
});
export const Property = IDL.Record({
  'status' : PropertyStatus,
  'latitude' : IDL.Float64,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'ownerId' : IDL.Principal,
  'plotBoundary' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'primaryImageIndex' : IDL.Nat,
  'description' : IDL.Text,
  'propertyId' : PropertyId,
  'viewCount' : IDL.Nat,
  'legalStatus' : LegalStatus,
  'constructionFields' : IDL.Opt(ConstructionSiteFields),
  'longitude' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'isConstructionSite' : IDL.Bool,
  'contactWhatsApp' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
  'locationName' : IDL.Text,
  'areaSizeSqFt' : IDL.Float64,
  'contactPhone' : IDL.Opt(IDL.Text),
  'dateAdded' : Timestamp,
  'images' : IDL.Vec(ExternalBlob),
});
export const DealerProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'photoUrl' : IDL.Text,
  'instagramUrl' : IDL.Text,
  'email' : IDL.Text,
  'experience' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'phone' : IDL.Text,
  'facebookUrl' : IDL.Text,
  'linkedinUrl' : IDL.Text,
});
export const UpdatePartnerInput = IDL.Record({
  'websiteUrl' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'logoUrl' : IDL.Opt(IDL.Text),
  'isVerified' : IDL.Opt(IDL.Bool),
  'contactEmail' : IDL.Opt(IDL.Text),
  'specialization' : IDL.Opt(IDL.Text),
  'contactPhone' : IDL.Opt(IDL.Text),
});
export const UpdatePropertyInput = IDL.Record({
  'latitude' : IDL.Opt(IDL.Float64),
  'title' : IDL.Opt(IDL.Text),
  'featured' : IDL.Opt(IDL.Bool),
  'plotBoundary' : IDL.Opt(IDL.Text),
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'primaryImageIndex' : IDL.Opt(IDL.Nat),
  'description' : IDL.Opt(IDL.Text),
  'legalStatus' : IDL.Opt(LegalStatus),
  'constructionFields' : IDL.Opt(ConstructionSiteFields),
  'longitude' : IDL.Opt(IDL.Float64),
  'notes' : IDL.Opt(IDL.Text),
  'isConstructionSite' : IDL.Opt(IDL.Bool),
  'contactWhatsApp' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Nat),
  'locationName' : IDL.Opt(IDL.Text),
  'areaSizeSqFt' : IDL.Opt(IDL.Float64),
  'contactPhone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addImageToProperty' : IDL.Func([PropertyId, ExternalBlob], [], []),
  'addPartner' : IDL.Func([AddPartnerInput], [IDL.Text], []),
  'addProperty' : IDL.Func([AddPropertyInput], [PropertyId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePartner' : IDL.Func([IDL.Text], [], []),
  'deleteProperty' : IDL.Func([PropertyId], [], []),
  'getAllPartners' : IDL.Func([], [IDL.Vec(BuilderPartner)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDealerProfile' : IDL.Func([], [IDL.Opt(DealerProfile)], ['query']),
  'getPartner' : IDL.Func([IDL.Text], [IDL.Opt(BuilderPartner)], ['query']),
  'getProperty' : IDL.Func([PropertyId], [IDL.Opt(Property)], ['query']),
  'incrementViewCount' : IDL.Func([PropertyId], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeImageFromProperty' : IDL.Func([PropertyId, IDL.Nat], [], []),
  'reorderImages' : IDL.Func([PropertyId, IDL.Vec(IDL.Nat)], [], []),
  'setDealerProfile' : IDL.Func([DealerProfile], [], []),
  'setPrimaryImageIndex' : IDL.Func([PropertyId, IDL.Nat], [], []),
  'setPropertyStatus' : IDL.Func([PropertyId, PropertyStatus], [], []),
  'updatePartner' : IDL.Func([IDL.Text, UpdatePartnerInput], [], []),
  'updateProperty' : IDL.Func([PropertyId, UpdatePropertyInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PropertyId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AddPartnerInput = IDL.Record({
    'websiteUrl' : IDL.Text,
    'name' : IDL.Text,
    'logoUrl' : IDL.Text,
    'isVerified' : IDL.Bool,
    'contactEmail' : IDL.Text,
    'specialization' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const LegalStatus = IDL.Variant({
    'not_approved' : IDL.Null,
    'approved' : IDL.Null,
  });
  const ConstructionSiteFields = IDL.Record({
    'currentPhase' : IDL.Text,
    'expectedCompletionDate' : IDL.Text,
    'constructionStartDate' : IDL.Text,
    'progressPercentage' : IDL.Nat,
    'sitePhotos' : IDL.Vec(ExternalBlob),
    'liveUpdates' : IDL.Text,
  });
  const AddPropertyInput = IDL.Record({
    'latitude' : IDL.Float64,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'plotBoundary' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'legalStatus' : LegalStatus,
    'constructionFields' : IDL.Opt(ConstructionSiteFields),
    'longitude' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'isConstructionSite' : IDL.Bool,
    'contactWhatsApp' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
    'locationName' : IDL.Text,
    'areaSizeSqFt' : IDL.Float64,
    'contactPhone' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const BuilderPartner = IDL.Record({
    'id' : IDL.Text,
    'websiteUrl' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'logoUrl' : IDL.Text,
    'isVerified' : IDL.Bool,
    'contactEmail' : IDL.Text,
    'specialization' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const PropertyStatus = IDL.Variant({
    'sold' : IDL.Null,
    'available' : IDL.Null,
  });
  const Property = IDL.Record({
    'status' : PropertyStatus,
    'latitude' : IDL.Float64,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'ownerId' : IDL.Principal,
    'plotBoundary' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'primaryImageIndex' : IDL.Nat,
    'description' : IDL.Text,
    'propertyId' : PropertyId,
    'viewCount' : IDL.Nat,
    'legalStatus' : LegalStatus,
    'constructionFields' : IDL.Opt(ConstructionSiteFields),
    'longitude' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'isConstructionSite' : IDL.Bool,
    'contactWhatsApp' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
    'locationName' : IDL.Text,
    'areaSizeSqFt' : IDL.Float64,
    'contactPhone' : IDL.Opt(IDL.Text),
    'dateAdded' : Timestamp,
    'images' : IDL.Vec(ExternalBlob),
  });
  const DealerProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'photoUrl' : IDL.Text,
    'instagramUrl' : IDL.Text,
    'email' : IDL.Text,
    'experience' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'phone' : IDL.Text,
    'facebookUrl' : IDL.Text,
    'linkedinUrl' : IDL.Text,
  });
  const UpdatePartnerInput = IDL.Record({
    'websiteUrl' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'logoUrl' : IDL.Opt(IDL.Text),
    'isVerified' : IDL.Opt(IDL.Bool),
    'contactEmail' : IDL.Opt(IDL.Text),
    'specialization' : IDL.Opt(IDL.Text),
    'contactPhone' : IDL.Opt(IDL.Text),
  });
  const UpdatePropertyInput = IDL.Record({
    'latitude' : IDL.Opt(IDL.Float64),
    'title' : IDL.Opt(IDL.Text),
    'featured' : IDL.Opt(IDL.Bool),
    'plotBoundary' : IDL.Opt(IDL.Text),
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'primaryImageIndex' : IDL.Opt(IDL.Nat),
    'description' : IDL.Opt(IDL.Text),
    'legalStatus' : IDL.Opt(LegalStatus),
    'constructionFields' : IDL.Opt(ConstructionSiteFields),
    'longitude' : IDL.Opt(IDL.Float64),
    'notes' : IDL.Opt(IDL.Text),
    'isConstructionSite' : IDL.Opt(IDL.Bool),
    'contactWhatsApp' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Nat),
    'locationName' : IDL.Opt(IDL.Text),
    'areaSizeSqFt' : IDL.Opt(IDL.Float64),
    'contactPhone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addImageToProperty' : IDL.Func([PropertyId, ExternalBlob], [], []),
    'addPartner' : IDL.Func([AddPartnerInput], [IDL.Text], []),
    'addProperty' : IDL.Func([AddPropertyInput], [PropertyId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePartner' : IDL.Func([IDL.Text], [], []),
    'deleteProperty' : IDL.Func([PropertyId], [], []),
    'getAllPartners' : IDL.Func([], [IDL.Vec(BuilderPartner)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDealerProfile' : IDL.Func([], [IDL.Opt(DealerProfile)], ['query']),
    'getPartner' : IDL.Func([IDL.Text], [IDL.Opt(BuilderPartner)], ['query']),
    'getProperty' : IDL.Func([PropertyId], [IDL.Opt(Property)], ['query']),
    'incrementViewCount' : IDL.Func([PropertyId], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeImageFromProperty' : IDL.Func([PropertyId, IDL.Nat], [], []),
    'reorderImages' : IDL.Func([PropertyId, IDL.Vec(IDL.Nat)], [], []),
    'setDealerProfile' : IDL.Func([DealerProfile], [], []),
    'setPrimaryImageIndex' : IDL.Func([PropertyId, IDL.Nat], [], []),
    'setPropertyStatus' : IDL.Func([PropertyId, PropertyStatus], [], []),
    'updatePartner' : IDL.Func([IDL.Text, UpdatePartnerInput], [], []),
    'updateProperty' : IDL.Func([PropertyId, UpdatePropertyInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };