/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ConstructionSiteFields {
    currentPhase: string;
    expectedCompletionDate: string;
    constructionStartDate: string;
    progressPercentage: bigint;
    sitePhotos: Array<ExternalBlob>;
    liveUpdates: string;
}
export interface AddPropertyInput {
    latitude: number;
    title: string;
    featured: boolean;
    plotBoundary?: string;
    tags: Array<string>;
    description: string;
    legalStatus: LegalStatus;
    constructionFields?: ConstructionSiteFields;
    longitude: number;
    notes?: string;
    isConstructionSite: boolean;
    contactWhatsApp?: string;
    price: bigint;
    locationName: string;
    areaSizeSqFt: number;
    contactPhone?: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BuilderPartner {
    id: string;
    websiteUrl: string;
    name: string;
    createdAt: Timestamp;
    logoUrl: string;
    isVerified: boolean;
    contactEmail: string;
    specialization: string;
    contactPhone: string;
}
export interface Property {
    status: PropertyStatus;
    latitude: number;
    title: string;
    featured: boolean;
    ownerId: Principal;
    plotBoundary?: string;
    tags: Array<string>;
    primaryImageIndex: bigint;
    description: string;
    propertyId: PropertyId;
    viewCount: bigint;
    legalStatus: LegalStatus;
    constructionFields?: ConstructionSiteFields;
    longitude: number;
    notes?: string;
    isConstructionSite: boolean;
    contactWhatsApp?: string;
    price: bigint;
    locationName: string;
    areaSizeSqFt: number;
    contactPhone?: string;
    dateAdded: Timestamp;
    images: Array<ExternalBlob>;
}
export interface DealerProfile {
    bio: string;
    name: string;
    designation: string;
    photoUrl: string;
    instagramUrl: string;
    email: string;
    experience: string;
    whatsappNumber: string;
    phone: string;
    facebookUrl: string;
    linkedinUrl: string;
}
export interface UpdatePartnerInput {
    websiteUrl?: string;
    name?: string;
    logoUrl?: string;
    isVerified?: boolean;
    contactEmail?: string;
    specialization?: string;
    contactPhone?: string;
}
export type PropertyId = string;
export interface AddPartnerInput {
    websiteUrl: string;
    name: string;
    logoUrl: string;
    isVerified: boolean;
    contactEmail: string;
    specialization: string;
    contactPhone: string;
}
export interface UpdatePropertyInput {
    latitude?: number;
    title?: string;
    featured?: boolean;
    plotBoundary?: string;
    tags?: Array<string>;
    primaryImageIndex?: bigint;
    description?: string;
    legalStatus?: LegalStatus;
    constructionFields?: ConstructionSiteFields;
    longitude?: number;
    notes?: string;
    isConstructionSite?: boolean;
    contactWhatsApp?: string;
    price?: bigint;
    locationName?: string;
    areaSizeSqFt?: number;
    contactPhone?: string;
}
export enum LegalStatus {
    not_approved = "not_approved",
    approved = "approved"
}
export enum PropertyStatus {
    sold = "sold",
    available = "available"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addImageToProperty(propertyId: PropertyId, image: ExternalBlob): Promise<void>;
    addPartner(input: AddPartnerInput): Promise<string>;
    addProperty(input: AddPropertyInput): Promise<PropertyId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deletePartner(partnerId: string): Promise<void>;
    deleteProperty(propertyId: PropertyId): Promise<void>;
    getAllPartners(): Promise<Array<BuilderPartner>>;
    getAllProperties(): Promise<Array<Property>>;
    getCallerUserRole(): Promise<UserRole>;
    getDealerProfile(): Promise<DealerProfile | null>;
    getPartner(partnerId: string): Promise<BuilderPartner | null>;
    getProperty(propertyId: PropertyId): Promise<Property | null>;
    incrementViewCount(propertyId: PropertyId): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    removeImageFromProperty(propertyId: PropertyId, imageIndex: bigint): Promise<void>;
    reorderImages(propertyId: PropertyId, newOrder: Array<bigint>): Promise<void>;
    setDealerProfile(profile: DealerProfile): Promise<void>;
    setPrimaryImageIndex(propertyId: PropertyId, index: bigint): Promise<void>;
    setPropertyStatus(propertyId: PropertyId, status: PropertyStatus): Promise<void>;
    updatePartner(partnerId: string, input: UpdatePartnerInput): Promise<void>;
    updateProperty(propertyId: PropertyId, input: UpdatePropertyInput): Promise<void>;
}
import type { AddPropertyInput as _AddPropertyInput, BuilderPartner as _BuilderPartner, ConstructionSiteFields as _ConstructionSiteFields, DealerProfile as _DealerProfile, ExternalBlob as _ExternalBlob, LegalStatus as _LegalStatus, Property as _Property, PropertyId as _PropertyId, PropertyStatus as _PropertyStatus, Timestamp as _Timestamp, UpdatePartnerInput as _UpdatePartnerInput, UpdatePropertyInput as _UpdatePropertyInput, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addImageToProperty(arg0: PropertyId, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addImageToProperty(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addImageToProperty(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addPartner(arg0: AddPartnerInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addPartner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPartner(arg0);
            return result;
        }
    }
    async addProperty(arg0: AddPropertyInput): Promise<PropertyId> {
        if (this.processError) {
            try {
                const result = await this.actor.addProperty(await to_candid_AddPropertyInput_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProperty(await to_candid_AddPropertyInput_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deletePartner(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePartner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePartner(arg0);
            return result;
        }
    }
    async deleteProperty(arg0: PropertyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProperty(arg0);
            return result;
        }
    }
    async getAllPartners(): Promise<Array<BuilderPartner>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPartners();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPartners();
            return result;
        }
    }
    async getAllProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProperties();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProperties();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDealerProfile(): Promise<DealerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDealerProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDealerProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartner(arg0: string): Promise<BuilderPartner | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartner(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartner(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: PropertyId): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementViewCount(arg0: PropertyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementViewCount(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeImageFromProperty(arg0: PropertyId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeImageFromProperty(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeImageFromProperty(arg0, arg1);
            return result;
        }
    }
    async reorderImages(arg0: PropertyId, arg1: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderImages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderImages(arg0, arg1);
            return result;
        }
    }
    async setDealerProfile(arg0: DealerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDealerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDealerProfile(arg0);
            return result;
        }
    }
    async setPrimaryImageIndex(arg0: PropertyId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPrimaryImageIndex(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPrimaryImageIndex(arg0, arg1);
            return result;
        }
    }
    async setPropertyStatus(arg0: PropertyId, arg1: PropertyStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPropertyStatus(arg0, to_candid_PropertyStatus_n36(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPropertyStatus(arg0, to_candid_PropertyStatus_n36(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePartner(arg0: string, arg1: UpdatePartnerInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePartner(arg0, to_candid_UpdatePartnerInput_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePartner(arg0, to_candid_UpdatePartnerInput_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProperty(arg0: PropertyId, arg1: UpdatePropertyInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProperty(arg0, await to_candid_UpdatePropertyInput_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProperty(arg0, await to_candid_UpdatePropertyInput_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ConstructionSiteFields_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConstructionSiteFields): Promise<ConstructionSiteFields> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LegalStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LegalStatus): LegalStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyStatus): PropertyStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_Property_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Promise<Property> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ConstructionSiteFields]): Promise<ConstructionSiteFields | null> {
    return value.length === 0 ? null : await from_candid_ConstructionSiteFields_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DealerProfile]): DealerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BuilderPartner]): BuilderPartner | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Property]): Promise<Property | null> {
    return value.length === 0 ? null : await from_candid_Property_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PropertyStatus;
    latitude: number;
    title: string;
    featured: boolean;
    ownerId: Principal;
    plotBoundary: [] | [string];
    tags: Array<string>;
    primaryImageIndex: bigint;
    description: string;
    propertyId: _PropertyId;
    viewCount: bigint;
    legalStatus: _LegalStatus;
    constructionFields: [] | [_ConstructionSiteFields];
    longitude: number;
    notes: [] | [string];
    isConstructionSite: boolean;
    contactWhatsApp: [] | [string];
    price: bigint;
    locationName: string;
    areaSizeSqFt: number;
    contactPhone: [] | [string];
    dateAdded: _Timestamp;
    images: Array<_ExternalBlob>;
}): Promise<{
    status: PropertyStatus;
    latitude: number;
    title: string;
    featured: boolean;
    ownerId: Principal;
    plotBoundary?: string;
    tags: Array<string>;
    primaryImageIndex: bigint;
    description: string;
    propertyId: PropertyId;
    viewCount: bigint;
    legalStatus: LegalStatus;
    constructionFields?: ConstructionSiteFields;
    longitude: number;
    notes?: string;
    isConstructionSite: boolean;
    contactWhatsApp?: string;
    price: bigint;
    locationName: string;
    areaSizeSqFt: number;
    contactPhone?: string;
    dateAdded: Timestamp;
    images: Array<ExternalBlob>;
}> {
    return {
        status: from_candid_PropertyStatus_n21(_uploadFile, _downloadFile, value.status),
        latitude: value.latitude,
        title: value.title,
        featured: value.featured,
        ownerId: value.ownerId,
        plotBoundary: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.plotBoundary)),
        tags: value.tags,
        primaryImageIndex: value.primaryImageIndex,
        description: value.description,
        propertyId: value.propertyId,
        viewCount: value.viewCount,
        legalStatus: from_candid_LegalStatus_n24(_uploadFile, _downloadFile, value.legalStatus),
        constructionFields: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.constructionFields)),
        longitude: value.longitude,
        notes: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.notes)),
        isConstructionSite: value.isConstructionSite,
        contactWhatsApp: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.contactWhatsApp)),
        price: value.price,
        locationName: value.locationName,
        areaSizeSqFt: value.areaSizeSqFt,
        contactPhone: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.contactPhone)),
        dateAdded: value.dateAdded,
        images: await from_candid_vec_n29(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPhase: string;
    expectedCompletionDate: string;
    constructionStartDate: string;
    progressPercentage: bigint;
    sitePhotos: Array<_ExternalBlob>;
    liveUpdates: string;
}): Promise<{
    currentPhase: string;
    expectedCompletionDate: string;
    constructionStartDate: string;
    progressPercentage: bigint;
    sitePhotos: Array<ExternalBlob>;
    liveUpdates: string;
}> {
    return {
        currentPhase: value.currentPhase,
        expectedCompletionDate: value.expectedCompletionDate,
        constructionStartDate: value.constructionStartDate,
        progressPercentage: value.progressPercentage,
        sitePhotos: await from_candid_vec_n29(_uploadFile, _downloadFile, value.sitePhotos),
        liveUpdates: value.liveUpdates
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sold: null;
} | {
    available: null;
}): PropertyStatus {
    return "sold" in value ? PropertyStatus.sold : "available" in value ? PropertyStatus.available : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    not_approved: null;
} | {
    approved: null;
}): LegalStatus {
    return "not_approved" in value ? LegalStatus.not_approved : "approved" in value ? LegalStatus.approved : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Promise<Array<Property>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Property_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, x)));
}
async function to_candid_AddPropertyInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddPropertyInput): Promise<_AddPropertyInput> {
    return await to_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function to_candid_ConstructionSiteFields_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConstructionSiteFields): Promise<_ConstructionSiteFields> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LegalStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LegalStatus): _LegalStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyStatus): _PropertyStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UpdatePartnerInput_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdatePartnerInput): _UpdatePartnerInput {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdatePropertyInput_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdatePropertyInput): Promise<_UpdatePropertyInput> {
    return await to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    title: string;
    featured: boolean;
    plotBoundary?: string;
    tags: Array<string>;
    description: string;
    legalStatus: LegalStatus;
    constructionFields?: ConstructionSiteFields;
    longitude: number;
    notes?: string;
    isConstructionSite: boolean;
    contactWhatsApp?: string;
    price: bigint;
    locationName: string;
    areaSizeSqFt: number;
    contactPhone?: string;
}): Promise<{
    latitude: number;
    title: string;
    featured: boolean;
    plotBoundary: [] | [string];
    tags: Array<string>;
    description: string;
    legalStatus: _LegalStatus;
    constructionFields: [] | [_ConstructionSiteFields];
    longitude: number;
    notes: [] | [string];
    isConstructionSite: boolean;
    contactWhatsApp: [] | [string];
    price: bigint;
    locationName: string;
    areaSizeSqFt: number;
    contactPhone: [] | [string];
}> {
    return {
        latitude: value.latitude,
        title: value.title,
        featured: value.featured,
        plotBoundary: value.plotBoundary ? candid_some(value.plotBoundary) : candid_none(),
        tags: value.tags,
        description: value.description,
        legalStatus: to_candid_LegalStatus_n11(_uploadFile, _downloadFile, value.legalStatus),
        constructionFields: value.constructionFields ? candid_some(await to_candid_ConstructionSiteFields_n13(_uploadFile, _downloadFile, value.constructionFields)) : candid_none(),
        longitude: value.longitude,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        isConstructionSite: value.isConstructionSite,
        contactWhatsApp: value.contactWhatsApp ? candid_some(value.contactWhatsApp) : candid_none(),
        price: value.price,
        locationName: value.locationName,
        areaSizeSqFt: value.areaSizeSqFt,
        contactPhone: value.contactPhone ? candid_some(value.contactPhone) : candid_none()
    };
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPhase: string;
    expectedCompletionDate: string;
    constructionStartDate: string;
    progressPercentage: bigint;
    sitePhotos: Array<ExternalBlob>;
    liveUpdates: string;
}): Promise<{
    currentPhase: string;
    expectedCompletionDate: string;
    constructionStartDate: string;
    progressPercentage: bigint;
    sitePhotos: Array<_ExternalBlob>;
    liveUpdates: string;
}> {
    return {
        currentPhase: value.currentPhase,
        expectedCompletionDate: value.expectedCompletionDate,
        constructionStartDate: value.constructionStartDate,
        progressPercentage: value.progressPercentage,
        sitePhotos: await to_candid_vec_n15(_uploadFile, _downloadFile, value.sitePhotos),
        liveUpdates: value.liveUpdates
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    websiteUrl?: string;
    name?: string;
    logoUrl?: string;
    isVerified?: boolean;
    contactEmail?: string;
    specialization?: string;
    contactPhone?: string;
}): {
    websiteUrl: [] | [string];
    name: [] | [string];
    logoUrl: [] | [string];
    isVerified: [] | [boolean];
    contactEmail: [] | [string];
    specialization: [] | [string];
    contactPhone: [] | [string];
} {
    return {
        websiteUrl: value.websiteUrl ? candid_some(value.websiteUrl) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        logoUrl: value.logoUrl ? candid_some(value.logoUrl) : candid_none(),
        isVerified: value.isVerified ? candid_some(value.isVerified) : candid_none(),
        contactEmail: value.contactEmail ? candid_some(value.contactEmail) : candid_none(),
        specialization: value.specialization ? candid_some(value.specialization) : candid_none(),
        contactPhone: value.contactPhone ? candid_some(value.contactPhone) : candid_none()
    };
}
async function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude?: number;
    title?: string;
    featured?: boolean;
    plotBoundary?: string;
    tags?: Array<string>;
    primaryImageIndex?: bigint;
    description?: string;
    legalStatus?: LegalStatus;
    constructionFields?: ConstructionSiteFields;
    longitude?: number;
    notes?: string;
    isConstructionSite?: boolean;
    contactWhatsApp?: string;
    price?: bigint;
    locationName?: string;
    areaSizeSqFt?: number;
    contactPhone?: string;
}): Promise<{
    latitude: [] | [number];
    title: [] | [string];
    featured: [] | [boolean];
    plotBoundary: [] | [string];
    tags: [] | [Array<string>];
    primaryImageIndex: [] | [bigint];
    description: [] | [string];
    legalStatus: [] | [_LegalStatus];
    constructionFields: [] | [_ConstructionSiteFields];
    longitude: [] | [number];
    notes: [] | [string];
    isConstructionSite: [] | [boolean];
    contactWhatsApp: [] | [string];
    price: [] | [bigint];
    locationName: [] | [string];
    areaSizeSqFt: [] | [number];
    contactPhone: [] | [string];
}> {
    return {
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        title: value.title ? candid_some(value.title) : candid_none(),
        featured: value.featured ? candid_some(value.featured) : candid_none(),
        plotBoundary: value.plotBoundary ? candid_some(value.plotBoundary) : candid_none(),
        tags: value.tags ? candid_some(value.tags) : candid_none(),
        primaryImageIndex: value.primaryImageIndex ? candid_some(value.primaryImageIndex) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        legalStatus: value.legalStatus ? candid_some(to_candid_LegalStatus_n11(_uploadFile, _downloadFile, value.legalStatus)) : candid_none(),
        constructionFields: value.constructionFields ? candid_some(await to_candid_ConstructionSiteFields_n13(_uploadFile, _downloadFile, value.constructionFields)) : candid_none(),
        longitude: value.longitude ? candid_some(value.longitude) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        isConstructionSite: value.isConstructionSite ? candid_some(value.isConstructionSite) : candid_none(),
        contactWhatsApp: value.contactWhatsApp ? candid_some(value.contactWhatsApp) : candid_none(),
        price: value.price ? candid_some(value.price) : candid_none(),
        locationName: value.locationName ? candid_some(value.locationName) : candid_none(),
        areaSizeSqFt: value.areaSizeSqFt ? candid_some(value.areaSizeSqFt) : candid_none(),
        contactPhone: value.contactPhone ? candid_some(value.contactPhone) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LegalStatus): {
    not_approved: null;
} | {
    approved: null;
} {
    return value == LegalStatus.not_approved ? {
        not_approved: null
    } : value == LegalStatus.approved ? {
        approved: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyStatus): {
    sold: null;
} | {
    available: null;
} {
    return value == PropertyStatus.sold ? {
        sold: null
    } : value == PropertyStatus.available ? {
        available: null
    } : value;
}
async function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
